name: Run it on action

on: 
    push:
      branches:
        - master
    schedule:
      - cron: '${{ secrets.CRON }}'
jobs:
  run-it:

    runs-on: ubuntu-latest

    steps:
    - name: 检出主分支
      uses: actions/checkout@master
    - name: 创建 python 环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.3'
        architecture: 'x64'
    - name: 执行
      run: |
        echo 'Notice.'
        echo '@Author: mybsdc <mybsdc@gmail.com>'
        echo '@Url: https://github.com/luolongfei/notice'

        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        cp .env.example .env
        if [[ '${{ secrets.MAIL_USERNAME }}' == '' || '${{ secrets.MAIL_PASSWORD }}' == '' || '${{ secrets.INBOX }}' == '' ]]; then echo '你在 Github 的当前项目的 Settings -> Secrets 画面缺少关键变量，无法正常执行。请分别设置 MAIL_USERNAME、MAIL_PASSWORD、INBOX 变量。'; fi
        if [ '${{ secrets.MAIL_USERNAME }}' != '' ]; then sed -i "s/^MAIL_USERNAME=.*$/MAIL_USERNAME='${{ secrets.MAIL_USERNAME }}'/" .env; fi
        if [ '${{ secrets.MAIL_PASSWORD }}' != '' ]; then sed -i "s/^MAIL_PASSWORD=.*$/MAIL_PASSWORD='${{ secrets.MAIL_PASSWORD }}'/" .env; fi
        if [ '${{ secrets.INBOX }}' != '' ]; then sed -i "s/^INBOX=.*$/INBOX='${{ secrets.INBOX }}'/" .env; fi

        python run.py