name: Run it on action

on: 
    push:
      branches:
        - master
    schedule:
      - cron: 00 02 * * *
jobs:
  run-it:

    runs-on: ubuntu-latest

    steps:
    - name: 检出主分支
      uses: actions/checkout@master
    - name: 创建 python 环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.3'
        architecture: 'x64'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 开始执行
      run: |
        python run.py